---
title: "課堂練習模版"
author: "吳永健"
date: "2020-10-07"
output: output_format
params:
  id: "410774205"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
a <- 15
b <- a
y <- 22
c <- y

myName <- "Mary"
length(myName) # 查看物件本身代表幾個值。

num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

```{r}
vNum1 <- vNum2
vNum2 <- C(2, vNum1)
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```
```{r}
hotec <- c()
hoatec <- sample(165:200,1)
```
```{r}
hotec <- c(hotec, hoatec)
```
```{r}
c(5, "Mary") #5也被當成文字 
c(5,7)
c(T,T,F,F)
```

```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
object.size(num1Vector)
object.size(num2Vector)
typeof(num1Vector)
typeof(num2Vector)
```
```{r}
char1<-"你好"
char2<-'你好'
char1Vector<-c("你好","How are you?")
class(char1Vector)
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
   '小花說："真的嗎？"')

dialogue # 顯示原始值的內容（含輸入時的引號）
cat(dialogue, sep="\n") # 顯示給人類看（含存出來）的值，sep="\n", 不同元素換行陳列。

```
```{r}
context <- '老師說換行要寫\\n' # 請依下列情境輸入 (再跳脫一次\)
cat(context)
```



